spring:
  application:
    name: ddd-ecommerce-order
  datasource:
    url: jdbc:h2:mem:ddd_order;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.ddd.ecommerce.order: debug