apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mall-cloud.labels" . | nindent 4 }}
data:
  # 共享环境变量：注册中心 / 监控 / 数据源公共项 / 探针上报地址
  TZ: "Asia/Shanghai"
  NACOS_ADDR: "{{ .Release.Name }}-nacos:8848"
  SENTINEL_DASHBOARD: "{{ .Release.Name }}-sentinel:8858"
  SENTINEL_PORT: "8719"
  SW_AGENT_COLLECTOR_BACKEND_SERVICES: "{{ .Release.Name }}-oap:11800"
  DB_HOST: "{{ .Release.Name }}-mysql"
  DB_PORT: "3306"
  SPRING_DATA_REDIS_HOST: "{{ .Release.Name }}-redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: ""
