apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mall-cloud.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.dbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | b64enc | quote }}
