apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mall-boot.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mall-boot.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.app.profile | quote }}
  DB_HOST: {{ tpl .Values.database.host $ | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  REDIS_HOST: {{ tpl .Values.redis.host $ | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  JWT_EXPIRE_HOURS: {{ .Values.app.jwtExpireHours | quote }}
  TZ: "Asia/Shanghai"
