apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mall-boot.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mall-boot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mall-boot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mall-boot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
              name: http
          # 环境注入：非敏感项走 ConfigMap，敏感项走 Secret（envFrom 整体注入）
          envFrom:
            - configMapRef:
                name: {{ include "mall-boot.fullname" . }}-config
            - secretRef:
                name: {{ include "mall-boot.fullname" . }}-secret
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
