apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mall-boot.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mall-boot.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | b64enc | quote }}
