apiVersion: v1
kind: Service
metadata:
  name: {{ include "mall-boot.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mall-boot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "mall-boot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: http
      protocol: TCP
      name: http
